### ISSUE TITLE
Getting None for Actor, Action  and Target objects

### ISSUE THREAD

**Issue by rohitnaidu19** [justquick/django-activity-stream#351]
I am able to insert the correct values for Actor, Action  and Target objects. I can also see these values in the Admin but when is use  `user_stream(request.user, with_user_activity=True)` i get `<Action: None  sent 1 hour, 22 minutes ago>]>`.  The Actor is None, Action is missing after 'sent'.
But when i do `Action.objects.all()` i get `<Action: Rocky sent Asap Email to Rahul 1 hour, 22 minutes ago>`. I guess there's an issue with the Manager.

Also `activity/feed/json/` return no data even though there are entries in Actions:
{
    "totalItems": 0,
    "items": []
}

If inserts are working in Actions and Follows table what could be the issue? I am using UUID fields as pk.

**Comment by rohitnaidu19** [comment]
I replaced all uuid fields with integer ids and it started working. Its an issue with UUID fields as primary keys. I tested with sqlite as well as Postgres. 

Feeds still returns empty dataset.

**Comment by auvipy** [comment]
As far I know UUID as primary key isn;t supported yet. or am I missing something? could you please check the doc and let us know?

**Comment by snwokenk** [comment]
I know this was closed. But I'm having the same issue. I realized this after having the same issue with two models and observing these were models with custom UUID primary keys. 

From other issues I was told it was a django issue and that it was fixed. I upgraded to django 2.2.1 but still having the same exact issue as @rohitnaidu19. 

so is UUID NOT supported?

**Comment by cobyrne09** [comment]
@snwokenk @auvipy. Was there any resolution to this? I updated to 2.2.2 based on  [https://github.com/justquick/django-activity-stream/issues/245](url) and am still having the same issue with UUIDS.
